services:
  game:
    build:
      context: ./apps/game
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./apps/game:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_TARGET=http://hack-spring2026-api:8800
      - WS_TARGET=ws://hack-spring2026-api:8800

  admin:
    build:
      context: ./apps/admin-panel
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - ./apps/admin-panel:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_TARGET=http://hack-spring2026-api:8800

