import type { EnemyType } from '../../core/GameState';
import type { DifficultyStage, EnemyTypeConfig } from './enemy.types';

export const ENEMY_TYPE_CONFIG: Record<EnemyType, EnemyTypeConfig> = {
    red: {
        textureKey:         'enemy',
        hp:                 1,
        hpMax:              1,
        speedMultiplier:    1.2,
        sizeMultiplier:     1.0,
        tapRadiusMultiplier: 0.65,
        tint:               null,
        hitTints:           [],
        deathFlashColor:    0x5f84ff,
        deathRingColor:     0x658bff,
        deathBitPalette:    ['#5145f1', '#7c33f3', '#6f51f3', '#6d53e4'],
        deathBurstScale:    1.0,
        deathDuration:      1.0,
        deathSpriteColor:   0x9cb5ff,
        trailLineColor:     0x1a0000,
        trailLineWidth:     31,
        trailGlyphColor:    '#cc1122',
        trailGlyphFontSize: 14,
        trailSampleDistPx:  5,
        trailMaxSamples:    11,
        trailGlyphCount:    9,
        trailRowCount:      3,
    },
    green: {
        textureKey:         'little-bro',
        hp:                 1,
        hpMax:              1,
        speedMultiplier:    2.4,
        sizeMultiplier:     0.65,
        tapRadiusMultiplier: 1.3,
        tint:               null,
        hitTints:           [],
        deathFlashColor:    0x44ff66,
        deathRingColor:     0x22cc44,
        deathBitPalette:    ['#22ff55', '#44ee44', '#88ff22', '#55dd33'],
        deathBurstScale:    0.7,
        deathDuration:      0.7,
        deathSpriteColor:   0x88ffaa,
        trailLineColor:     0x001400,
        trailLineWidth:     22,
        trailGlyphColor:    '#22cc44',
        trailGlyphFontSize: 11,
        trailSampleDistPx:  4,
        trailMaxSamples:    8,
        trailGlyphCount:    4,
        trailRowCount:      2,
    },
    blue: {
        textureKey:         'big-bro',
        hp:                 3,
        hpMax:              6,
        speedMultiplier:    0.456,
        sizeMultiplier:     1.35,
        tapRadiusMultiplier: 0.65,
        tint:               null,
        hitTints:           [0xff4466, 0xff8899, 0xbbddff, 0x99ddff, 0xcceeff],
        deathFlashColor:    0x44aaff,
        deathRingColor:     0x2288ee,
        deathBitPalette:    ['#2277ff', '#4499ff', '#66bbff', '#88ccff', '#aaddff'],
        deathBurstScale:    1.6,
        deathDuration:      1.5,
        deathSpriteColor:   0x88ccff,
        trailLineColor:     0x000033,
        trailLineWidth:     30,
        trailGlyphColor:    '#4499ff',
        trailGlyphFontSize: 17,
        trailSampleDistPx:  5,
        trailMaxSamples:    14,
        trailGlyphCount:    12,
        trailRowCount:      3,
    },
    orange: {
        textureKey:         'orange-enemy',
        hp:                 1,
        hpMax:              1,
        speedMultiplier:    1.3,
        sizeMultiplier:     0.9,
        tapRadiusMultiplier: 0.65,
        tint:               null,
        hitTints:           [],
        deathFlashColor:    0xff8800,
        deathRingColor:     0xdd6600,
        deathBitPalette:    ['#ff8800', '#ffaa22', '#ffcc44', '#dd6600', '#ff5500'],
        deathBurstScale:    1.2,
        deathDuration:      1.0,
        deathSpriteColor:   0xffaa44,
        trailLineColor:     0x1a0800,
        trailLineWidth:     42,
        trailGlyphColor:    '#ff8800',
        trailGlyphFontSize: 13,
        trailSampleDistPx:  5,
        trailMaxSamples:    8,
        trailGlyphCount:    6,
        trailRowCount:      3,
    },
};

export const DIFFICULTY_STAGES: DifficultyStage[] = [
    {
        fromMs:             0,
        maxEnemies:         5,
        minSpawnIntervalMs: 1200,
        maxSpawnIntervalMs: 1600,
        minSpeed:           55,
        maxSpeed:           70,
        typeWeights:        { red: 1 },
    },
    {
        fromMs:             15_000,
        maxEnemies:         6,
        minSpawnIntervalMs: 1400,
        maxSpawnIntervalMs: 1900,
        minSpeed:           60,
        maxSpeed:           80,
        typeWeights:        { red: 4, blue: 1 },
    },
    {
        fromMs:             40_000,
        maxEnemies:         7,
        minSpawnIntervalMs: 1100,
        maxSpawnIntervalMs: 1550,
        minSpeed:           68,
        maxSpeed:           90,
        typeWeights:        { red: 3, blue: 2, green: 1 },
    },
    {
        fromMs:             80_000,
        maxEnemies:         8,
        minSpawnIntervalMs: 850,
        maxSpawnIntervalMs: 1250,
        minSpeed:           75,
        maxSpeed:           102,
        typeWeights:        { red: 3, blue: 2, green: 2, orange: 1 },
    },
    {
        fromMs:             120_000,
        maxEnemies:         10,
        minSpawnIntervalMs: 600,
        maxSpawnIntervalMs: 920,
        minSpeed:           84,
        maxSpeed:           116,
        typeWeights:        { red: 3, blue: 2, green: 2, orange: 1 },
    },
    {
        fromMs:             180_000,
        maxEnemies:         13,
        minSpawnIntervalMs: 350,
        maxSpawnIntervalMs: 600,
        minSpeed:           96,
        maxSpeed:           138,
        typeWeights:        { red: 3, blue: 2, green: 3, orange: 2 },
    },
];
